### PR TITLE
LPS-99221

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @yxingwu, thanks for working on this and sending this over!

We were working on this on the Clay side, since the base component is still vulnerable to the XSS attack. We fixed this on clay at https://github.com/liferay/clay/pull/2272 and I've sent a PR updating portal with the new version at https://github.com/brianchandotcom/liferay-portal/pull/77034

This should be safer for everyone using both the wrapped component or the base one rather than just fixing it in the top-level one we offer on Portal.

Could you please verify that the sent solution also addresses the issue?

Thanks!

**Comment by yxingwu** [comment]
Hi @jbalsas ,
I can't reproduce [LPS-99221](https://issues.liferay.com/browse/LPS-99221) any more .
It was fixed by the sent solution.

Regards.

**Comment by samuelkong** [comment]
@jbalsas 
I took a look at your changes in https://github.com/liferay/clay/pull/2272 and I think there's some problem with that fix. My comments are in https://github.com/liferay/clay/pull/2272.

**Comment by jbalsas** [comment]
Thanks a lot @samuelkong, we'll take a look over there!

**Pull request closed without merging**
