### PR TITLE
LPS-88643 update spring dependencies

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
result of "ci:test": https://github.com/yxingwu/liferay-portal/pull/89

**Comment by samuelkong** [comment]
Thanks. Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/7315

**Comment by samuelkong** [comment]
Thanks. Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/7315

**Pull request closed without merging**
