### PR TITLE
Lps 96095 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@samuelkong 
PR seems fine with ci:test:relevant

**Comment by samuelkong** [comment]
Thanks. Trying again. https://github.com/brianchandotcom/liferay-portal/pull/74479

**Pull request closed without merging**
