### PR TITLE
Lps 95290 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Guys,

Please make sure it goes through the Collab's team review too. Thanks!

**Comment by samuelkong** [comment]
Thanks. Sent to https://github.com/adolfopa/liferay-portal/pull/1002

**Pull request closed without merging**
