### PR TITLE
LPS-77722

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test

**Comment by yxingwu** [comment]
ci:retest

**Comment by yxingwu** [comment]
ci:test

**Comment by samuelkong** [comment]
Thanks. Forwarded to https://github.com/liferay/liferay-portal-ee/pull/5494

Note: I didn't include https://github.com/samuelkong/liferay-portal/pull/836/commits/45957cb018ad85220cd8d60b329d94e7e192f59f

**Comment by samuelkong** [comment]
Thanks forwarded to https://github.com/brianchandotcom/liferay-portal/pull/56022

**Comment by samuelkong** [comment]
ci:stop

**Pull request closed without merging**
