### PR TITLE
Lps 96095 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
master-private PR:
https://github.com/samuelkong/liferay-portal-ee/pull/67

sf issues should be fixed by master-priavete PR.
the only relevant error in ci:test:relevant has been solved by https://github.com/samuelkong/liferay-portal/pull/969/commits/b63140c2329d470b2cc6295b6123855bc35da1a4

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by samuelkong** [comment]
Everything has been merged into master. Thanks.

**Pull request closed without merging**
