### PR TITLE
LPS-55951 Fix typo

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
I have also made a change to your code in https://github.com/sergiogonzalez/liferay-portal/commit/394a1119006ed958e41a4455cb373ccb96603a7c

Thanks!

**Comment by samuelkong** [comment]
@sergiogonzalez Thanks for catching that.

Regarding the escape: You might have noticed that I sent you another pull request but then closed it again. I basically need more time to investigate the issue. We're doing something really weird here.

In `document_library/search_resources.jsp`, we sometimes escaping the title/description and sometimes not.

And then in `AppViewSearchEntryTag.java`, we do an `HtmlUtil#unescape` on the title/description. (This is the part I'm confused about. Need to figure out why we're doing this)

And finally, we escape the title/description again in `app_view_search_entry/page.jsp`.

**Comment by samuelkong** [comment]
Thanks. Sent to Julio. https://github.com/juliocamarero/liferay-portal/pull/3440

**Comment by sergiogonzalez** [comment]
Got it. Thanks @samuelkong

**Pull request closed without merging**
