### PR TITLE
Lps 72939 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
c:test

**Comment by samuelkong** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by samuelkong** [comment]
Can you do the following:
1. Check if it's possible to do a redirect with a relative URL that doesn't start with a `/`
2. Add test cases for `getDomain` and `escapeRedirect`

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by samuelkong** [comment]
Can you redo your test. You're using t.com and example.com but none of the other tests are using these domains.

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by samuelkong** [comment]
Can you create a new pull request instead of reopening. Thanks.

**Pull request closed without merging**
