### PR TITLE
LPS-57258 Wiki titles containing EN DASH are HTML HEX entity escaped

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @samuelkong I think that you are a better reviewer for this pull than me. Can you check it and let @IstvanD know if you have any question.

Thanks!

-----

Hey @sergiogonzalez 

Could you please check this pull?

This may not necessary be a Collaboration related issue/solution, if so, please feel free to redirect it to the appropriate reviewer.

Thanks,
István

### CODE REVIEW

**Comment by samuelkong** [comment]
@IstvanD 

This isn't the correct solution. Instead we should properly escape the URL in wiki/page_iterator.jsp

**Comment by IstvanD** [comment]
Hi @samuelkong 

Thanks for the reply.

The Wiki Page title is autoescaped thanks to the curWikiPage turning into an EscapedModel.

```java
curWikiPage = curWikiPage.toEscapedModel();
...
rowURL.setParameter("title", HtmlUtil.unescape(curWikiPage.getTitle()));
```

Should then the toEscapedModel() and HTMLUtil.unescape() calls omitted?

The code would look like this then:

```java
rowURL.setParameter("title", curWikiPage.getTitle());
```

Thanks,
István

**Comment by samuelkong** [comment]
Yes, you'll need to remove the call to `toEscapeModel()` and `HtmlUtil.escape()`. But you'll also need to go back and add in the escape to all the other places that was depending on the `toEscapeModel()`

**Pull request closed without merging**
