### PR TITLE
LPS-77403

### PR DESCRIPTION
**Pull request by topolik**
Hi Sam,

I reverted the ticket that caused this regression. For performance reasons they removed whole security layer. 

/cc @pavel-savinov

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by samuelkong** [comment]
ci:reopen

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
ci:retest

**Comment by topolik** [comment]
ci:stop

Hi Sam, the test fail is real. The log message changed. I fix it. Sorry I didn't notice it earlier.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/54946. Thanks.

**Pull request closed without merging**
