### PR TITLE
LPS-57329

### PR DESCRIPTION
**Pull request by neilking**

### CODE REVIEW

**Comment by samuelkong** [comment]
Hey Neil

I think a cleaner solution is to disable the form fields using JavaScript. When you you have the on submit event, disable the textarea so that the form value doesn't get submitted.

Can you also make this change to
* Facebook callback URL
* OpenSocial Gadget URL
* Netvibes Widdget URL

**Comment by neilking** [comment]
Actually in our 6.2 code it removes the name attribute in html to prevent it to be submitted. And see our  <liferay-ui:input-resource> taglib.

**Comment by neilking** [comment]
for the URLs  we can keep the current code, it's just 1 line, they can use aui input [type=resource]

**Comment by neilking** [comment]
I will make this change to the javascripts.

**Comment by samuelkong** [comment]
Thanks for the explanation. Sent to Brian. https://github.com/brianchandotcom/liferay-portal/pull/32485

**Pull request closed without merging**
