### PR TITLE
Lps 96095 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
$ ant test-class -Dtest.class=JSONUtilTest
Buildfile: /home/arthurchan35/Liferay/ce/source/portal-impl/build.xml
   [delete] Deleting: /home/arthurchan35/Liferay/ce/source/null976938779.properties

download-latest-artifact:

build-common-java.init-compile:

init-compile:

build-common-java.compile:

compile:
     [echo] June 5, 2019 at 10:03 AM

test-class:
    [mkdir] Created dir: /home/arthurchan35/Liferay/ce/source/portal-impl/test-classes/unit
    [mkdir] Created dir: /home/arthurchan35/Liferay/ce/source/portal-impl/test-results/unit
     [copy] Copying 47 files to /home/arthurchan35/Liferay/ce/source/portal-impl/test-classes/unit
    [javac] Compiling 245 source files to /home/arthurchan35/Liferay/ce/source/portal-impl/test-classes/unit
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [echo] test.cmd.start.timestamp: 06-04-2019 19:03:31:715 PDT
    [junit] Running com.liferay.portal.json.JSONUtilTest
    [junit] Testsuite: com.liferay.portal.json.JSONUtilTest
    [junit] SLF4J: Class path contains multiple SLF4J bindings.
    [junit] SLF4J: Found binding in [file:/home/arthurchan35/Liferay/ce/source/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
    [junit] SLF4J: Found binding in [jar:file:/home/arthurchan35/Liferay/ce/source/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    [junit] Loading file:/home/arthurchan35/Liferay/ce/source/portal-impl/classes/system.properties
    [junit] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    [junit] SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
    [junit] Loading file:/home/arthurchan35/Liferay/ce/source/portal-impl/classes/portal.properties
    [junit] Loading file:/home/arthurchan35/Liferay/ce/source/portal-impl/test-classes/unit/portal-test.properties
    [junit] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.345 sec
    [junit] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.345 sec
    [junit] 
[stopwatch] [test.cmd: 0.964 sec]

BUILD SUCCESSFUL
Total time: 4 seconds

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by samuelkong** [comment]
Can you check if my changes are ok. Thanks.

**Comment by samuelkong** [comment]
https://github.com/arthurchan35/liferay-portal/pull/29

**Pull request closed without merging**
