### PR TITLE
Lps 72939 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
run tests first

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci: retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:test

**Comment by samuelkong** [comment]
Thanks. Forwarded to https://github.com/shuyangzhou/liferay-portal/pull/5866

**Pull request closed without merging**
