### PR TITLE
LPS-60598

### PR DESCRIPTION
**Pull request by topolik**
Hi Sam,

sending this for review to you. I just noticed it already has a rich history where you did some analysis (https://github.com/samuelkong/liferay-portal/pull/741).

I thought this is a wrong fix, but maybe it aligns with some refactorings that are still pending. So my findings may not be correct, please see https://github.com/topolik/liferay-portal/pull/303#issuecomment-192304609.

Thanks.

### CODE REVIEW

**Comment by samuelkong** [comment]
Thanks. Sent to Brian. https://github.com/brianchandotcom/liferay-portal/pull/37312

**Comment by samuelkong** [comment]
Sorry, closed the wrong PR.

**Comment by samuelkong** [comment]
I don't think this is the correct solution.

Let's assume, we have the following language key:
`language-key=Language &gt; Key`

Before the change the following:

    String message = "language-key";
    <liferay-ui:message key="<%= HtmlUtil.escapeAttribute(message) %>" />

will print `Language &gt; Key` in the HTML source or, equivalently, `Language > Key` in the browser

After the change,

    String message = "language-key";
    <liferay-ui:message escapeAttribute="<%= true %>" key="<%= message %>" />

will print `Language &amp;gt; Key` in the HTML source or, equivalently, `Language &gt; Key` in the browser.

**Comment by samuelkong** [comment]
eerrrr... brain not working...Didn't see Neil's commit.

**Comment by neilking** [comment]
Based on your assumption, I think you assume the translations are unescapable value then the escape and escapeAttribute attribute of liferay-ui:message are not needed at all.

**Comment by samuelkong** [comment]
Ok, my comment still applies.
* Also, I just realized that escapeAttribute should have converted the `>` character to `&#x3e;` instead of `&gt;`. But hopefully, you got the right idea.

@neilking

**Comment by samuelkong** [comment]
@neilking 
No, I'm not assuming that. The problem is the `message` can be a language key or it can be user inputted text.

If `message` is a language key, the translated text is actually usually escaped already. So in this case, the escapes are not needed.

However, if the `message` is user inputted text, then it needs to be escaped.

**Comment by neilking** [comment]
I think the so called user-inputted value is the value it can't be found in language properties file. Suppose we have "language-key= Language Key" in properties file, but user intend to output "language-key", it will not output language-key as the user wanted. Still your assumption is based on the translation is already escaped and unescapable.

**Comment by samuelkong** [comment]
@neilking You're looking at it the wrong way. The behavior of the taglib is to first look up the `message` in the Language file. If the `message` is in the Language file, the translated text is expected to be escaped already. Therefore this translated text should not be escaped again. However, if the `message` is not in the Language file, then the `message` itself is used. In this case the `message` needs to be escaped.

So if there is a "language-key" in the Language file, the user would wrong to expect it to output "language-key".

**Comment by neilking** [comment]
Emm, why there's translated text like "all-applications-export-help=The configuration of all applications is exported. The export of archived setups and user preferences can be disabled by using the <em>Change</em> option."     in language.properties.

**Comment by neilking** [comment]
all-applications-export-help=The configuration of all applications is exported. The export of archived setups and user preferences can be disabled by using the < em > Change < / e m > option.

**Comment by neilking** [comment]
Why there's something like this in language.properties?

**Comment by samuelkong** [comment]
The `<em>` is there because we want "Change" to be in italics. And as a result, the whole sentence, cannot be escaped (i.e., it's already escaped)

**Comment by neilking** [comment]
So what would you do in this case? Escape for user input, but not escape for language key?

**Comment by samuelkong** [comment]
Yes.

**Comment by neilking** [comment]
in liferay-ui:message implementation or in liferay-ui:icon implementation?

**Comment by samuelkong** [comment]
liferay-ui:message

**Comment by neilking** [comment]
Thanks!

**Pull request closed without merging**
