### PR TITLE
LPS-80155 refer rfc2254, encode some special characters in filter

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test

**Comment by yxingwu** [comment]
ci:retest

**Comment by yxingwu** [comment]
ci:stop

**Comment by yxingwu** [comment]
ci:test

**Comment by samuelkong** [comment]
Thanks. Forwarded to https://github.com/topolik/liferay-portal/pull/573

**Pull request closed without merging**
